### ISSUE TITLE
Provide support for additional docker container params

### ISSUE THREAD

**Issue by fvet** [gunnargestsson/AdvaniaGIT#10]
When trying to build my first NAV environment, I run into the following error, that is thrown by the command to create a docker container:

_Hostname is 4b512a4078cd
PublicDnsName is 4b512a4078cd
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying NAV Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Using license file 'C:\Host\License\NAV2018.flf'
Import NAV License
Creating DotNetCore NAV Web Server Instance
Creating http download site
Creating Windows user Administrator
Setting SA Password and enabling SA
Creating NAV user
**Cannot index into a null array.**
at <ScriptBlock>, C:\Run\navstart.ps1: line 172
at <ScriptBlock>, C:\Run\start.ps1: line 102
at <ScriptBlock>, <No file>: line 1_

I ran into similar issues when manually creating containers via New-CSideContainer (navcontainerhelper), since I'm using a local VM, where I need to set the IP different per container.  (See https://www.kauffmann.nl/2017/12/02/running-nav-docker-containers-on-a-local-hyper-v-virtual-machine/) 

I've added following param to the New-CSideContainer commandlet:

_-additionalParameters @("--network=tlan","--ip 172.21.31.xx")_

Can you embed this as a JSON parameter somewhere, so it can be used in Start-Dockercontainer1 when you spin up new containers? When hardcoding the param, it seems to work, so apparently this would fix it.

**Comment by gunnargestsson** [comment]
Yes this error is because the container does not have an ip address.
Adding two parameters to DockerSettings.json

   "DockerHostIPName":  "tlan",
    "DockerHostIPNetwork":  "172.21.31.",

should fix this.

**Comment by gunnargestsson** [comment]
But to tell you right now.  AdvaniaGIT does not support containers running on VM unless you run AdvaniaGIT on the VM
