### ISSUE TITLE
Error - Implement me. Unknown stdin file type!

### ISSUE THREAD

**Issue by fvet** [gunnargestsson/AdvaniaGIT#11]
When building the NAV container, all succeeds except for the last step, which is the copy of the container vsix file (ok) and install on my local VS code (fails)

_Copying AL Extension to Host Computer...
Implement me. Unknown stdin file type!_

Trying to manually run the VSIX (via explorer) from the logs folder, gives an eror with following log:

_20/03/2018 23:59:09 - Microsoft VSIX Installer
20/03/2018 23:59:09 - -------------------------------------------
20/03/2018 23:59:10 - Initializing Install...
20/03/2018 23:59:10 - Extension Details...
20/03/2018 23:59:10 - 	Identifier      : al
20/03/2018 23:59:10 - 	Name            : AL Language
20/03/2018 23:59:10 - 	Author          : Microsoft
20/03/2018 23:59:10 - 	Version         : 0.12.17720
20/03/2018 23:59:10 - 	Description     : Extension development support for Dynamics NAV
20/03/2018 23:59:10 - 	Locale          : en-US
20/03/2018 23:59:10 - 	MoreInfoURL     : 
20/03/2018 23:59:10 - 	InstalledByMSI  : False
20/03/2018 23:59:10 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
20/03/2018 23:59:10 - 
20/03/2018 23:59:10 - 	Supported Products : 
20/03/2018 23:59:10 - 		Microsoft.VisualStudio.Code
20/03/2018 23:59:10 - 			Version : 
20/03/2018 23:59:10 - 
20/03/2018 23:59:10 - 	References      : 
20/03/2018 23:59:10 - 
20/03/2018 23:59:10 - Searching for applicable products...
20/03/2018 23:59:10 - Found installed product - Global Location
20/03/2018 23:59:10 - Found installed product - ssms
20/03/2018 23:59:10 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()_

Trying to manually install the vsix from within VSCode gives a warning (since I already had the NAV devpreview installed earlier) that can be confirmed:

_A newer version is already available of the extension ... Override?_

Anything the scripts can take care off?

**Comment by gunnargestsson** [comment]
Can you retry this and list all the steps you take if the error persist.
