### ISSUE TITLE
PDFFontEmbedding is not valid property for Report

### ISSUE THREAD

**Issue by gnatthapol** [gunnargestsson/AdvaniaGIT#13]
Hi,
I tried to run `NAV Modified > GIT` and got the warning message after run this action.

> Exporting modified files...
> WARNING: C:\AdvaniaGIT\Workspace\Target.txt (12,21) PDFFontEmbedding is not valid property for Report.
> WARNING: C:\AdvaniaGIT\Workspace\Target.txt (12,21) PDFFontEmbedding is not valid property for Report.

In both of Sourcetree screen and repository folder, I can't find exported report objects that the value of property `PDFFontEmbedding
` isn't set as default (both of `Yes` and `No`). When I change it to default, it can be run without any errors.

Could you check this problem?

**Comment by gunnargestsson** [comment]
is this possibly a version conflict between the text file export and the tools used?
