### ISSUE TITLE
Feed url for NAV 2018 has been changed

### ISSUE THREAD

**Issue by tomasevicstefan** [gunnargestsson/AdvaniaGIT#19]
Did you know that feed url for Nav 2018 has been changed? Do you have new one?

**Comment by tomasevicstefan** [comment]
We can generate feed and atom url here (https://support.microsoft.com/en-ca/help/4089498/support-content-updates), but my only doubt is that guid that is contain in url will be different after next release

**Comment by gunnargestsson** [comment]
Do we need some online source or a config file that holds links to the download urls for versions and cus?
