### ISSUE TITLE
FTP server on different port

### ISSUE THREAD

**Issue by epernst** [gunnargestsson/AdvaniaGIT#4]
Hi Gunnar,

Having a problem using the FTP functions. It "dies" in the GetResponse when it first connect to the FTP server. The scripts fails with this message:
System.Management.Automation.MethodInvocationException Exception calling "GetResponse" with "0" argument(s): "Unable to connect to the remote server"

Line is  **$FTPResponse = $FTPRequest.GetResponse()** in Get-FtpDirectory.ps1

My guess is that it fails because my FTP server is on a different port. It seems according to [this post](https://social.msdn.microsoft.com/forums/en-US/bc1e643a-75b4-4176-98c9-16d75daf6764/ftpwebrequest-specify-a-data-port-to-use) not to be possible. Instead I tried the suggested change of adding a line:
$FTPRequest.UsePassive = $True

That doesn't change anything. Any suggestions?

**Comment by gunnargestsson** [comment]
Do you have used, pass and server configured in GITSettings.json ?
