### ISSUE TITLE
Import-NAVApplicationObject Namespace in Powershell overwritten

### ISSUE THREAD

**Issue by Nody85** [gunnargestsson/AdvaniaGIT#5]
Hello Gunnar,

i have installed your Dynamics Nav / Git Integration.
After the installation was my Import-NAVApplicationObject command not the same anymore.
It showes on Mouseover it comes from the modul "AdvantiaGit" and has other Parameters.

**Comment by gunnargestsson** [comment]
Have removed this one from the module.  Should not be there...
Sorry

**Comment by Nody85** [comment]
No Problem. I am very glad to found your solution.
