### ISSUE TITLE
'Join-NAVApplicationObjectFile' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by kaspermoerch** [gunnargestsson/AdvaniaGIT#6]
When using the commands `Export GIT Objects to Source.txt in Work Folder` and `Export GIT Objects to Modified.txt in Work Folder` the following error occurs:

`System.Management.Automation.CommandNotFoundException The term 'Join-NAVApplicationObjectFile' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

I am running AdvaniaGIT through Visual Studio Code and using NAV on Docker: `microsoft/dynamics-nav:2018-cu1-dk`.

**Comment by gunnargestsson** [comment]
I believe I fixed this one today.
Go through Advania: Go! to update.

**Comment by kaspermoerch** [comment]
I installed the new version of the VS Code extension and ran `Advania: Go!`.

It works as expected now.
