### ISSUE TITLE
Error When creating new environment with Docker Container

### ISSUE THREAD

**Issue by nickrobbo** [gunnargestsson/AdvaniaGIT#9]
Hi, 
I have the following setup.json file 

`{
    "branchId": "6d2fccad-c54a-48fd-a02c-5a0649d633dd",
    "navVersion": "10.0.16177.0",
    "navSolution": "***",
    "projectName": "***",
    "storeAllObjects": "true",
    "objectProperties": "true",
    "dateTimeCulture": "en-GB",
    "dockerImage": "microsoft/dynamics-nav:2017-cu5-gb"
  }
  `
I have removed the solution name and project name in this case for privacy. 

I have found that I have to copy this setup.json file out of the folder for my repository (which I cloned into the Workspace folder).  I have to move it into the Workspace folder specifically for any of the commands to work.  It seems that the setup file can't be found?

My second issue is that I get this error message when starting the container using the build environment command. (see attached).  I have removed the image, and re-run the command and still get the same error. 

![image](https://user-images.githubusercontent.com/35219805/35817209-aa631acc-0a94-11e8-85f4-03ec6d806be9.png)

**Comment by gunnargestsson** [comment]
HI
This is an error returned from the Docker deamon.
Make sure that the Docker deamon is running and responding to command line functions like

docker ps

and then try again.

**Comment by gunnargestsson** [comment]
the setup.json needs to be in the root of your GIT repository.  I usually have a subfolder GIT in my workspace and from there subfolders for servers and then for repositories.
Example: Workspace\GIT\Advania\NAV2018
This is the folder you need to open in Visual Studio Code.
